### ISSUE TITLE
부트 프로젝트 생성

### ISSUE THREAD

**Issue by Sonny-in-1999** [Sonny-in-1999/mini-board-project#1]
뷰트 이니셜라이져를 통해 초기 프로젝트를 생성합니다.

아래 의존성을 추가할 계획입니다.
- 스프링 웹
- 액츄에이터
- 롬복
- 데브툴즈

**Comment by Sonny-in-1999** [comment]
@Atsilut @Marge00 

멘션 테스트 입니다. 수신확인 부탁드립니다.

**Comment by Atsilut** [comment]
const NMH = '씹섹스'
